---
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: amqp
spec:
  replicas: 1
  tls:
    secretName: amqp-tls-secret
  rabbitmq:
    additionalConfig: |
      ssl_options.fail_if_no_peer_cert = true
